keys:
  - &primary age1ndqndvxdq8ska77f6adw0ec3f86ahuqttfz4ex5q7jqr20uy8vyquxkpml
  - &kian_yubikey age1yubikey1qf2tnrupt04gnr9c37sjm2kddcpxcnu5fu6v3jhzjreekg6clwmmz6h3gq0
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *primary
      - *kian_yubikey
